id: P007033
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W8LS17842
  title: ཆོ་འཕྲུལ་ཆེན་མོའི་རྟོགས་བརྗོད།
  author: ''
  volumes:
    9b18271604d248249037e22169f53e88:
      image_group_id: I8LS17873
      title: Volume 1 of cho 'phrul chen mo'i rtogs brjod/
      volume_number: 1
      total_pages: 76
      base_file: v001.txt
