id: P007033
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS17842
  title: ཆོ་འཕྲུལ་ཆེན་མོའི་རྟོགས་བརྗོད།
  author: ''
  volumes:
    c7dfaad766c1434aab115444ebe1ef47:
      image_group_id: I8LS17873
      title: ''
      volume_number: 1
      total_pages: 76
ebook_metadata:
  title: ཆོ་འཕྲུལ་ཆེན་མོའི་རྟོགས་བརྗོད།
  author: ''
  sku: P007033
  cover: cover.jpg
  layers:
  - pagination
