id: I11FEC63E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T00:18:55+00:00'
last_modified: '2022-06-08T13:27:17.749843+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS17842
  title: ཆོ་འཕྲུལ་ཆེན་མོའི་རྟོགས་བརྗོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D962:
      image_group_id: I8LS17873
      title: Volume 1 of cho 'phrul chen mo'i rtogs brjod/
      total_pages: 76
      order: 1
      base_file: D962.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
